from typing import Optional, List, Dict

class Device:
    def __init__(self, path: str) -> None: ...
    def read(self, amount: int, timeout: Optional[int] = None) -> bytes: ...
    def close(self) -> None: ...

def enumerate(vendor_id: int, product_id: int) -> List[Dict[str, str]]: ...
